"""
Config package for Yvynation Reflex app.
Imports all configuration constants from config.py
"""

from .config import (
    PROJECT_ID,
    MAPBIOMAS_COLLECTIONS,
    HANSEN_DATASETS,
    HANSEN_OCEAN_MASK,
    HANSEN_GFC_DATASET,
    HANSEN_GFC_TREE_COVER_VIS,
    HANSEN_GFC_TREE_LOSS_VIS,
    HANSEN_GFC_TREE_GAIN_VIS,
    MAPBIOMAS_LABELS,
    MAPBIOMAS_COLOR_MAP,
    MAPBIOMAS_PALETTE,
    HANSEN_PALETTE,
    HANSEN_COLOR_MAP,
    HANSEN_CONSOLIDATED_MAPPING,
    HANSEN_CONSOLIDATED_COLORS,
    REGION_OF_INTEREST,
    OUTPUT_BUCKET,
    OUTPUT_SCALE,
    MAPBIOMAS_YEARS,
    HANSEN_YEARS,
)

__all__ = [
    "PROJECT_ID",
    "MAPBIOMAS_COLLECTIONS",
    "HANSEN_DATASETS",
    "HANSEN_OCEAN_MASK",
    "HANSEN_GFC_DATASET",
    "HANSEN_GFC_TREE_COVER_VIS",
    "HANSEN_GFC_TREE_LOSS_VIS",
    "HANSEN_GFC_TREE_GAIN_VIS",
    "MAPBIOMAS_LABELS",
    "MAPBIOMAS_COLOR_MAP",
    "MAPBIOMAS_PALETTE",
    "HANSEN_PALETTE",
    "HANSEN_COLOR_MAP",
    "HANSEN_CONSOLIDATED_MAPPING",
    "HANSEN_CONSOLIDATED_COLORS",
    "REGION_OF_INTEREST",
    "OUTPUT_BUCKET",
    "OUTPUT_SCALE",
    "MAPBIOMAS_YEARS",
    "HANSEN_YEARS",
]
