"""Explanatory text for the laid-out territory report (docs/PDF_REPORT.md §2.8, §3a).

Deterministic templates in en (reference and fallback), pt, es and fr. Every
sentence is filled from the same records the section's chart and table are
drawn from — nothing is recomputed here beyond sums and shares of those rows.

**Describe, never judge.** Sentences state quantities, changes over the period
and differences between the territory and its buffer. They never attribute a
change to a cause, to protection or to governance, and carry no legal or
compliance vocabulary. The causal reading belongs to the offline governance
reports in ``utils/``, not to a per-area export.

Numbers are formatted by ``report_kit.text`` so a Portuguese report reads
"1.234,5 ha" and an English one "1,234.5 ha".
"""

from __future__ import annotations

from typing import Dict, List, Optional, Sequence, Tuple

from ..report_kit.text import fmt_ha, fmt_num, fmt_pct
from ..report_kit.text import fmt_signed as _kit_signed


def fmt_signed(value, decimals: int = 1, lang: str = "en") -> str:
    """The kit's signed number with an ASCII hyphen for the minus: the kit's
    Noto Sans subset has no U+2212, so its true minus prints as a blank in
    the PDF (reported upstream; drop this wrapper once the kit is fixed)."""
    return _kit_signed(value, decimals, lang).replace("\u2212", "-")


LANGS = ("en", "pt", "es", "fr")

TEXT: Dict[str, Dict[str, str]] = {
    # ------------------------------------------------------------------ en
    "en": {
        "report_title": "Territory report",
        "kind_ti": "Indigenous Land",
        "kind_uc": "Conservation Unit",
        "sec_identification": "Identification",
        "sec_about": "About this report",
        "sec_maps": "Maps",
        "sec_landcover": "Land cover {y1} vs {y2}",
        "sec_gains_losses": "Gains and losses",
        "sec_transitions": "Transitions",
        "sec_gfc": "Hansen Global Forest Change",
        "sec_glad": "GLAD land cover",
        "sec_multi_window": "Multi-window transitions",
        "sec_timeline": "Deforestation timeline",
        "sec_buffer": "Territory vs buffer",
        "sec_methods": "Methods and data",
        "sec_citation": "Sources and citation",
        "sec_appendix": "Appendix",
        # identification
        "id_name": "Name",
        "id_code": "FUNAI code",
        "id_ethnicity": "Ethnic group(s)",
        "id_phase": "Phase",
        "id_modality": "Modality",
        "id_uf": "State(s)",
        "id_municipality": "Municipality(ies)",
        "id_area_official": "Official area",
        "id_area_computed": "Computed area (MapBiomas {y})",
        "id_ladder": "Demarcation stages",
        "stage_em_estudo": "in study",
        "stage_delimitada": "delimited",
        "stage_declarada": "declared",
        "stage_homologada": "homologated",
        "stage_regularizada": "regularised",
        "id_cnuc": "CNUC code",
        "id_group": "Group",
        "id_category": "Category",
        "id_sphere": "Sphere",
        "id_creation_year": "Year of creation",
        "id_years": "Years compared",
        "id_mapbiomas": "MapBiomas collection",
        "id_gfc": "Hansen GFC",
        "id_glad": "GLAD land cover",
        "id_buffer": "Buffer",
        "id_buffer_width": "{km} km ring around the boundary",
        "id_not_analysed": "not analysed",
        "id_caption_ti": "Attributes from the FUNAI boundary file; computed area from MapBiomas pixel counts.",
        "id_caption_uc": "Attributes from the CNUC boundary file; computed area from MapBiomas pixel counts.",
        "locator_label": "Location in Brazil",
        # about
        "about_para": "This report covers **{name}**{period}{buffer}. It presents data, not a verdict: the numbers describe what each dataset records inside the boundary, and differences between years or between the territory and its surroundings are stated without attributing them to any cause.",
        "about_period": " for the years {y1} and {y2}",
        "about_buffer": ", with a {km} km buffer around it",
        "about_quadrants": "The area was analysed in {n} parts that are summed in every table and chart.",
        "reason_not_run": "not run for this area",
        "reason_excluded": "excluded by the report options",
        "reason_no_buffer": "no buffer was analysed",
        "reason_maps_failed": "the map images could not be fetched",
        "reason_appendix_batch": "not produced in batch runs",
        "contents_appendix": "Appendix (full tables)",
        # maps
        "maps_intro": "Class layers and imagery come from Earth Engine; outlines are drawn from the boundary file. The solid line is the territory boundary and the dashed line the outer edge of the buffer.",
        "map_mb_caption": "MapBiomas land cover, {y}.",
        "map_gfc_caption": "Year of tree-cover loss (Hansen GFC, 2001–2025) over the imagery backdrop.",
        "map_img_caption": "Imagery backdrop with the territory boundary and buffer.",
        "maps_no_imagery": "The area spans more than 300 km, so no imagery backdrop is drawn; class layers are shown on a blank background.",
        "maps_failed": "The map images could not be fetched from Earth Engine: {err}",
        "legend_boundary": "Territory boundary",
        "legend_buffer": "Buffer ({km} km)",
        "legend_loss": "Loss {a}–{b}",
        # land cover
        "lc_intro": "MapBiomas Collection 10.1 classifies every 30 m pixel of Brazil into land-cover and land-use classes for each year since 1985.",
        "lc_fig_caption": "Area per land-cover class inside the territory, {y1} and {y2}.",
        "lc_table_caption": "Land-cover classes inside the territory, {y1} vs {y2}.",
        "lc_reading": "Between {y1} and {y2}, {cls} inside the territory went from {a1} ({p1}) to {a2} ({p2}), {direction}.",
        "dir_up": "an increase of {d}",
        "dir_down": "a decrease of {d}",
        "dir_same": "with no change",
        "lc_second_up": "{cls} grew by {d}.",
        "lc_second_down": "{cls} shrank by {d}.",
        "col_class": "Class",
        "col_area_y": "{y} (ha)",
        "col_delta_ha": "Change (ha)",
        "col_delta_pct": "Change (%)",
        "col_share": "Share (%)",
        # gains / losses
        "gl_intro": "Net change per class between {y1} and {y2}: positive bars are area gained, negative bars area lost.",
        "gl_fig_caption": "Gains and losses per land-cover class, {y1}–{y2}.",
        "gl_reading": "Summed over all classes, gains total {g} and losses {l}. The largest gain is in {cg} ({dg}) and the largest loss in {cl} ({dl}).",
        # transitions
        "tr_intro": "Transitions give the area of pixels that changed class between {y1} and {y2}; pixels that kept their class are not counted.",
        "tr_fig_caption": "Land-cover transitions, {y1}–{y2}.",
        "tr_table_caption": "The ten largest transitions, {y1}–{y2}.",
        "tr_reading": "In total, {total} changed class. The largest transition was from {a} to {b} ({ha}, {pct} of the changed area).",
        "tr_none": "No pixel changed class between the two years.",
        "col_from": "From ({y})",
        "col_to": "To ({y})",
        "col_area_ha": "Area (ha)",
        "col_share_changed": "% of changed area",
        # GFC
        "gfc_intro": "Hansen Global Forest Change (UMD, v1.13) maps tree-canopy cover in 2000, the year of stand-replacing tree-cover loss from 2001 to 2025, and tree-cover gain between 2000 and 2012, at 30 m.",
        "gfc_fig_caption": "Tree-cover loss per year inside the territory (Hansen GFC).",
        "gfc_table_caption": "Hansen GFC summary for the territory.",
        "gfc_m_cover": "Tree cover in 2000 (canopy > 0%)",
        "gfc_m_loss": "Total loss 2001–{last}",
        "gfc_m_loss_pct": "Loss as % of the 2000 tree cover",
        "gfc_m_gain": "Gain 2000–2012 (undated)",
        "gfc_reading": "Hansen records {loss} of tree-cover loss from 2001 to {last}, {pct} of the 2000 tree cover; the largest single year was {year} ({ha}).",
        "gfc_reading_none": "Hansen records no tree-cover loss inside the territory from 2001 to 2025.",
        "col_metric": "Metric",
        "col_value": "Value",
        # GLAD
        "glad_intro": "GLAD GLCLU2020 (v2) maps global land cover and land use at 30 m for 2000, 2005, 2010, 2015 and 2020.",
        "glad_fig_caption": "GLAD land-cover classes inside the territory, {year}.",
        "glad_table_caption": "The five largest GLAD classes, {year}.",
        "glad_reading": "In {year}, the largest GLAD class inside the territory was {cls}, with {ha} ({pct} of the classified area).",
        # multi-window
        "mw_intro": "The multi-window analysis chains MapBiomas transitions across consecutive windows: {years}.",
        "mw_fig_caption": "Land-cover transitions across {n} windows, {first}–{last}.",
        # timeline
        "tl_intro": "Annual series of tree-cover loss and related MapBiomas indicators inside the territory, {y0}–{y1}.",
        "tl_fig_caption": "Deforestation timeline, {y0}–{y1}.",
        "tl_note": "The coloured bands behind the series mark political terms and policy milestones. They are reference points in time only; the chart does not attribute any change to them.",
        # buffer
        "buf_intro": "The buffer is a ring of {km} km around the territory, analysed with the same datasets and years.",
        "buf_table_caption": "Territory and buffer compared.",
        "buf_forest_note": "Forest = MapBiomas natural forest classes 3, 4, 5, 6 and 49; pp = percentage points.",
        "buf_m_forest_y": "Forest cover {y} (%)",
        "buf_m_forest_change": "Change in forest cover {y1}–{y2} (pp)",
        "buf_m_gfc": "GFC loss, % of the 2000 tree cover",
        "buf_reading": "Over the same period, forest cover changed by {t} pp inside the territory and by {b} pp in its {km} km buffer, a difference of {gap} pp.",
        "buf_reading_gfc": "Hansen loss amounts to {t} of the 2000 tree cover inside the territory and {b} in the buffer.",
        "col_territory": "Territory",
        "col_buffer": "Buffer",
        "col_difference": "Buffer minus territory",
        # methods
        "methods_intro": "Datasets, bands, scales and reducers behind each section. The report reuses the analysis results; nothing was recomputed at export.",
        "prov_mapbiomas": "MapBiomas land cover",
        "prov_transitions": "MapBiomas transitions",
        "prov_gfc": "Hansen GFC",
        "prov_glad": "GLAD land cover",
        "prov_mw": "Multi-window transitions",
        "prov_timeline": "Deforestation timeline",
        "prov_imagery": "Map imagery",
        "prov_buffer": "Buffer",
        "prov_note_area": "Area = pixel count × mean pixel area of the region at 30 m.",
        "prov_note_buffer": "External ring of {km} km around the boundary, analysed with the same datasets.",
        "prov_note_quadrants": "Analysed in {n} parts and summed.",
        "prov_note_timeline": "Hansen loss per year plus MapBiomas deforestation, secondary vegetation and fire series.",
        "prov_note_imagery": "Used only as a map backdrop, not in any number.",
        "prov_note_transitions": "Change-only: pixels that kept their class are excluded.",
        # citation
        "attr_mapbiomas": "MapBiomas Project, Collection 10.1 — CC BY-SA 4.0",
        "attr_hansen": "Hansen/UMD/Google/USGS/NASA, Global Forest Change — CC BY 4.0",
        "attr_glad": "GLAD/UMD, GLCLU2020 — CC BY 4.0",
        "attr_ti": "Indigenous Land boundaries and attributes: FUNAI",
        "attr_uc": "Conservation Unit boundaries and attributes: CNUC/MMA",
        "attr_ibge": "State boundaries (locator map): IBGE",
        # appendix
        "app_classes_caption": "All land-cover classes inside the territory, {y}.",
        "app_change_pct_caption": "Relative change per land-cover class, {y1}–{y2}.",
        "app_buffer_cmp_caption": "Buffer: area per land-cover class, {y1} and {y2}.",
        "app_buffer_gl_caption": "Buffer: gains and losses per land-cover class, {y1}–{y2}.",
        "app_buffer_classes_caption": "All land-cover classes in the buffer, {y1} vs {y2}.",
        "app_matrix_caption": "Transition matrix, {y1}–{y2}.",
        "app_transitions_caption": "All transitions, {y1}–{y2}.",
        "fig_render_failed": "the chart could not be rendered",
    },
    # ------------------------------------------------------------------ pt
    "pt": {
        "report_title": "Relatório territorial",
        "kind_ti": "Terra Indígena",
        "kind_uc": "Unidade de Conservação",
        "sec_identification": "Identificação",
        "sec_about": "Sobre este relatório",
        "sec_maps": "Mapas",
        "sec_landcover": "Cobertura do solo {y1} vs {y2}",
        "sec_gains_losses": "Ganhos e perdas",
        "sec_transitions": "Transições",
        "sec_gfc": "Hansen Global Forest Change",
        "sec_glad": "Cobertura do solo GLAD",
        "sec_multi_window": "Transições em múltiplas janelas",
        "sec_timeline": "Linha do tempo do desmatamento",
        "sec_buffer": "Território vs buffer",
        "sec_methods": "Métodos e dados",
        "sec_citation": "Fontes e citação",
        "sec_appendix": "Apêndice",
        "id_name": "Nome",
        "id_code": "Código FUNAI",
        "id_ethnicity": "Etnia(s)",
        "id_phase": "Fase",
        "id_modality": "Modalidade",
        "id_uf": "UF",
        "id_municipality": "Município(s)",
        "id_area_official": "Área oficial",
        "id_area_computed": "Área calculada (MapBiomas {y})",
        "id_ladder": "Etapas da demarcação",
        "stage_em_estudo": "em estudo",
        "stage_delimitada": "delimitada",
        "stage_declarada": "declarada",
        "stage_homologada": "homologada",
        "stage_regularizada": "regularizada",
        "id_cnuc": "Código CNUC",
        "id_group": "Grupo",
        "id_category": "Categoria",
        "id_sphere": "Esfera",
        "id_creation_year": "Ano de criação",
        "id_years": "Anos comparados",
        "id_mapbiomas": "Coleção MapBiomas",
        "id_gfc": "Hansen GFC",
        "id_glad": "Cobertura do solo GLAD",
        "id_buffer": "Buffer",
        "id_buffer_width": "anel de {km} km em torno do limite",
        "id_not_analysed": "não analisado",
        "id_caption_ti": "Atributos do arquivo de limites da FUNAI; área calculada a partir da contagem de pixels do MapBiomas.",
        "id_caption_uc": "Atributos do arquivo de limites do CNUC; área calculada a partir da contagem de pixels do MapBiomas.",
        "locator_label": "Localização no Brasil",
        "about_para": "Este relatório trata de **{name}**{period}{buffer}. Ele apresenta dados, não um veredito: os números descrevem o que cada conjunto de dados registra dentro do limite, e as diferenças entre anos ou entre o território e seu entorno são descritas sem atribuí-las a nenhuma causa.",
        "about_period": " nos anos de {y1} e {y2}",
        "about_buffer": ", com um buffer de {km} km ao redor",
        "about_quadrants": "A área foi analisada em {n} partes, somadas em todas as tabelas e gráficos.",
        "reason_not_run": "não calculado para esta área",
        "reason_excluded": "excluído nas opções do relatório",
        "reason_no_buffer": "nenhum buffer foi analisado",
        "reason_maps_failed": "as imagens dos mapas não puderam ser obtidas",
        "reason_appendix_batch": "não gerado em processamentos em lote",
        "contents_appendix": "Apêndice (tabelas completas)",
        "maps_intro": "As camadas de classes e as imagens vêm do Earth Engine; os contornos são desenhados a partir do arquivo de limites. A linha contínua é o limite do território e a tracejada, a borda externa do buffer.",
        "map_mb_caption": "Cobertura do solo MapBiomas, {y}.",
        "map_gfc_caption": "Ano da perda de cobertura arbórea (Hansen GFC, 2001–2025) sobre a imagem de fundo.",
        "map_img_caption": "Imagem de fundo com o limite do território e o buffer.",
        "maps_no_imagery": "A área tem mais de 300 km de extensão, por isso nenhuma imagem de fundo é desenhada; as camadas de classes aparecem sobre fundo branco.",
        "maps_failed": "As imagens dos mapas não puderam ser obtidas do Earth Engine: {err}",
        "legend_boundary": "Limite do território",
        "legend_buffer": "Buffer ({km} km)",
        "legend_loss": "Perda {a}–{b}",
        "lc_intro": "A Coleção 10.1 do MapBiomas classifica cada pixel de 30 m do Brasil em classes de cobertura e uso do solo para cada ano desde 1985.",
        "lc_fig_caption": "Área por classe de cobertura do solo dentro do território, {y1} e {y2}.",
        "lc_table_caption": "Classes de cobertura do solo dentro do território, {y1} vs {y2}.",
        "lc_reading": "Entre {y1} e {y2}, {cls} dentro do território passou de {a1} ({p1}) para {a2} ({p2}), {direction}.",
        "dir_up": "um aumento de {d}",
        "dir_down": "uma redução de {d}",
        "dir_same": "sem alteração",
        "lc_second_up": "{cls} cresceu {d}.",
        "lc_second_down": "{cls} diminuiu {d}.",
        "col_class": "Classe",
        "col_area_y": "{y} (ha)",
        "col_delta_ha": "Variação (ha)",
        "col_delta_pct": "Variação (%)",
        "col_share": "Participação (%)",
        "gl_intro": "Variação líquida por classe entre {y1} e {y2}: barras positivas são área ganha, barras negativas, área perdida.",
        "gl_fig_caption": "Ganhos e perdas por classe de cobertura do solo, {y1}–{y2}.",
        "gl_reading": "Somando todas as classes, os ganhos totalizam {g} e as perdas {l}. O maior ganho ocorre em {cg} ({dg}) e a maior perda em {cl} ({dl}).",
        "tr_intro": "As transições dão a área dos pixels que mudaram de classe entre {y1} e {y2}; pixels que mantiveram a classe não são contados.",
        "tr_fig_caption": "Transições de cobertura do solo, {y1}–{y2}.",
        "tr_table_caption": "As dez maiores transições, {y1}–{y2}.",
        "tr_reading": "No total, {total} mudaram de classe. A maior transição foi de {a} para {b} ({ha}, {pct} da área alterada).",
        "tr_none": "Nenhum pixel mudou de classe entre os dois anos.",
        "col_from": "De ({y})",
        "col_to": "Para ({y})",
        "col_area_ha": "Área (ha)",
        "col_share_changed": "% da área alterada",
        "gfc_intro": "O Hansen Global Forest Change (UMD, v1.13) mapeia a cobertura do dossel arbóreo em 2000, o ano da perda de cobertura arbórea por substituição do povoamento de 2001 a 2025 e o ganho de cobertura arbórea entre 2000 e 2012, a 30 m.",
        "gfc_fig_caption": "Perda de cobertura arbórea por ano dentro do território (Hansen GFC).",
        "gfc_table_caption": "Resumo Hansen GFC do território.",
        "gfc_m_cover": "Cobertura arbórea em 2000 (dossel > 0%)",
        "gfc_m_loss": "Perda total 2001–{last}",
        "gfc_m_loss_pct": "Perda como % da cobertura arbórea de 2000",
        "gfc_m_gain": "Ganho 2000–2012 (sem data)",
        "gfc_reading": "O Hansen registra {loss} de perda de cobertura arbórea entre 2001 e {last}, {pct} da cobertura de 2000; o maior ano foi {year} ({ha}).",
        "gfc_reading_none": "O Hansen não registra perda de cobertura arbórea dentro do território entre 2001 e 2025.",
        "col_metric": "Indicador",
        "col_value": "Valor",
        "glad_intro": "O GLAD GLCLU2020 (v2) mapeia a cobertura e o uso do solo global a 30 m para 2000, 2005, 2010, 2015 e 2020.",
        "glad_fig_caption": "Classes de cobertura do solo GLAD dentro do território, {year}.",
        "glad_table_caption": "As cinco maiores classes GLAD, {year}.",
        "glad_reading": "Em {year}, a maior classe GLAD dentro do território foi {cls}, com {ha} ({pct} da área classificada).",
        "mw_intro": "A análise em múltiplas janelas encadeia as transições do MapBiomas em janelas consecutivas: {years}.",
        "mw_fig_caption": "Transições de cobertura do solo em {n} janelas, {first}–{last}.",
        "tl_intro": "Séries anuais de perda de cobertura arbórea e indicadores relacionados do MapBiomas dentro do território, {y0}–{y1}.",
        "tl_fig_caption": "Linha do tempo do desmatamento, {y0}–{y1}.",
        "tl_note": "As faixas coloridas atrás das séries marcam mandatos políticos e marcos de políticas públicas. São apenas referências no tempo; o gráfico não atribui nenhuma mudança a elas.",
        "buf_intro": "O buffer é um anel de {km} km ao redor do território, analisado com os mesmos conjuntos de dados e anos.",
        "buf_table_caption": "Território e buffer comparados.",
        "buf_forest_note": "Floresta = classes de floresta natural do MapBiomas 3, 4, 5, 6 e 49; p.p. = pontos percentuais.",
        "buf_m_forest_y": "Cobertura florestal {y} (%)",
        "buf_m_forest_change": "Variação da cobertura florestal {y1}–{y2} (p.p.)",
        "buf_m_gfc": "Perda GFC, % da cobertura arbórea de 2000",
        "buf_reading": "No mesmo período, a cobertura florestal variou {t} p.p. dentro do território e {b} p.p. no buffer de {km} km, uma diferença de {gap} p.p.",
        "buf_reading_gfc": "A perda Hansen equivale a {t} da cobertura arbórea de 2000 dentro do território e a {b} no buffer.",
        "col_territory": "Território",
        "col_buffer": "Buffer",
        "col_difference": "Buffer menos território",
        "methods_intro": "Conjuntos de dados, bandas, escalas e redutores de cada seção. O relatório reutiliza os resultados da análise; nada foi recalculado na exportação.",
        "prov_mapbiomas": "Cobertura do solo MapBiomas",
        "prov_transitions": "Transições MapBiomas",
        "prov_gfc": "Hansen GFC",
        "prov_glad": "Cobertura do solo GLAD",
        "prov_mw": "Transições em múltiplas janelas",
        "prov_timeline": "Linha do tempo do desmatamento",
        "prov_imagery": "Imagens dos mapas",
        "prov_buffer": "Buffer",
        "prov_note_area": "Área = número de pixels × área média do pixel da região a 30 m.",
        "prov_note_buffer": "Anel externo de {km} km em torno do limite, analisado com os mesmos dados.",
        "prov_note_quadrants": "Analisado em {n} partes e somado.",
        "prov_note_timeline": "Perda Hansen por ano, mais as séries MapBiomas de desmatamento, vegetação secundária e fogo.",
        "prov_note_imagery": "Usadas apenas como fundo dos mapas, em nenhum número.",
        "prov_note_transitions": "Apenas mudanças: pixels que mantiveram a classe são excluídos.",
        "attr_mapbiomas": "Projeto MapBiomas, Coleção 10.1 — CC BY-SA 4.0",
        "attr_hansen": "Hansen/UMD/Google/USGS/NASA, Global Forest Change — CC BY 4.0",
        "attr_glad": "GLAD/UMD, GLCLU2020 — CC BY 4.0",
        "attr_ti": "Limites e atributos das Terras Indígenas: FUNAI",
        "attr_uc": "Limites e atributos das Unidades de Conservação: CNUC/MMA",
        "attr_ibge": "Limites estaduais (mapa de localização): IBGE",
        "app_classes_caption": "Todas as classes de cobertura do solo dentro do território, {y}.",
        "app_change_pct_caption": "Variação relativa por classe de cobertura do solo, {y1}–{y2}.",
        "app_buffer_cmp_caption": "Buffer: área por classe de cobertura do solo, {y1} e {y2}.",
        "app_buffer_gl_caption": "Buffer: ganhos e perdas por classe de cobertura do solo, {y1}–{y2}.",
        "app_buffer_classes_caption": "Todas as classes de cobertura do solo no buffer, {y1} vs {y2}.",
        "app_matrix_caption": "Matriz de transições, {y1}–{y2}.",
        "app_transitions_caption": "Todas as transições, {y1}–{y2}.",
        "fig_render_failed": "não foi possível gerar o gráfico",
    },
    # ------------------------------------------------------------------ es
    "es": {
        "report_title": "Informe territorial",
        "kind_ti": "Tierra Indígena",
        "kind_uc": "Unidad de Conservación",
        "sec_identification": "Identificación",
        "sec_about": "Acerca de este informe",
        "sec_maps": "Mapas",
        "sec_landcover": "Cobertura del suelo {y1} vs {y2}",
        "sec_gains_losses": "Ganancias y pérdidas",
        "sec_transitions": "Transiciones",
        "sec_gfc": "Hansen Global Forest Change",
        "sec_glad": "Cobertura del suelo GLAD",
        "sec_multi_window": "Transiciones en múltiples ventanas",
        "sec_timeline": "Línea de tiempo de la deforestación",
        "sec_buffer": "Territorio vs zona de amortiguamiento",
        "sec_methods": "Métodos y datos",
        "sec_citation": "Fuentes y citación",
        "sec_appendix": "Apéndice",
        "id_name": "Nombre",
        "id_code": "Código FUNAI",
        "id_ethnicity": "Pueblo(s)",
        "id_phase": "Fase",
        "id_modality": "Modalidad",
        "id_uf": "Estado(s)",
        "id_municipality": "Municipio(s)",
        "id_area_official": "Superficie oficial",
        "id_area_computed": "Superficie calculada (MapBiomas {y})",
        "id_ladder": "Etapas de la demarcación",
        "stage_em_estudo": "en estudio",
        "stage_delimitada": "delimitada",
        "stage_declarada": "declarada",
        "stage_homologada": "homologada",
        "stage_regularizada": "regularizada",
        "id_cnuc": "Código CNUC",
        "id_group": "Grupo",
        "id_category": "Categoría",
        "id_sphere": "Esfera",
        "id_creation_year": "Año de creación",
        "id_years": "Años comparados",
        "id_mapbiomas": "Colección MapBiomas",
        "id_gfc": "Hansen GFC",
        "id_glad": "Cobertura del suelo GLAD",
        "id_buffer": "Zona de amortiguamiento",
        "id_buffer_width": "anillo de {km} km alrededor del límite",
        "id_not_analysed": "no analizada",
        "id_caption_ti": "Atributos del archivo de límites de la FUNAI; superficie calculada a partir del conteo de píxeles de MapBiomas.",
        "id_caption_uc": "Atributos del archivo de límites del CNUC; superficie calculada a partir del conteo de píxeles de MapBiomas.",
        "locator_label": "Ubicación en Brasil",
        "about_para": "Este informe trata de **{name}**{period}{buffer}. Presenta datos, no un veredicto: las cifras describen lo que cada conjunto de datos registra dentro del límite, y las diferencias entre años o entre el territorio y su entorno se describen sin atribuirlas a ninguna causa.",
        "about_period": " para los años {y1} y {y2}",
        "about_buffer": ", con una zona de amortiguamiento de {km} km a su alrededor",
        "about_quadrants": "El área se analizó en {n} partes que se suman en todas las tablas y gráficos.",
        "reason_not_run": "no calculado para esta área",
        "reason_excluded": "excluido en las opciones del informe",
        "reason_no_buffer": "no se analizó ninguna zona de amortiguamiento",
        "reason_maps_failed": "no se pudieron obtener las imágenes de los mapas",
        "reason_appendix_batch": "no se genera en los procesamientos por lotes",
        "contents_appendix": "Apéndice (tablas completas)",
        "maps_intro": "Las capas de clases y las imágenes provienen de Earth Engine; los contornos se dibujan a partir del archivo de límites. La línea continua es el límite del territorio y la discontinua, el borde exterior de la zona de amortiguamiento.",
        "map_mb_caption": "Cobertura del suelo MapBiomas, {y}.",
        "map_gfc_caption": "Año de pérdida de cobertura arbórea (Hansen GFC, 2001–2025) sobre la imagen de fondo.",
        "map_img_caption": "Imagen de fondo con el límite del territorio y la zona de amortiguamiento.",
        "maps_no_imagery": "El área supera los 300 km de extensión, por lo que no se dibuja imagen de fondo; las capas de clases se muestran sobre fondo blanco.",
        "maps_failed": "No se pudieron obtener las imágenes de los mapas desde Earth Engine: {err}",
        "legend_boundary": "Límite del territorio",
        "legend_buffer": "Zona de amortiguamiento ({km} km)",
        "legend_loss": "Pérdida {a}–{b}",
        "lc_intro": "La Colección 10.1 de MapBiomas clasifica cada píxel de 30 m de Brasil en clases de cobertura y uso del suelo para cada año desde 1985.",
        "lc_fig_caption": "Superficie por clase de cobertura del suelo dentro del territorio, {y1} y {y2}.",
        "lc_table_caption": "Clases de cobertura del suelo dentro del territorio, {y1} vs {y2}.",
        "lc_reading": "Entre {y1} y {y2}, {cls} dentro del territorio pasó de {a1} ({p1}) a {a2} ({p2}), {direction}.",
        "dir_up": "un aumento de {d}",
        "dir_down": "una disminución de {d}",
        "dir_same": "sin cambios",
        "lc_second_up": "{cls} creció {d}.",
        "lc_second_down": "{cls} disminuyó {d}.",
        "col_class": "Clase",
        "col_area_y": "{y} (ha)",
        "col_delta_ha": "Variación (ha)",
        "col_delta_pct": "Variación (%)",
        "col_share": "Proporción (%)",
        "gl_intro": "Variación neta por clase entre {y1} y {y2}: las barras positivas son superficie ganada, las negativas, superficie perdida.",
        "gl_fig_caption": "Ganancias y pérdidas por clase de cobertura del suelo, {y1}–{y2}.",
        "gl_reading": "Sumando todas las clases, las ganancias totalizan {g} y las pérdidas {l}. La mayor ganancia se da en {cg} ({dg}) y la mayor pérdida en {cl} ({dl}).",
        "tr_intro": "Las transiciones indican la superficie de los píxeles que cambiaron de clase entre {y1} y {y2}; los píxeles que mantuvieron su clase no se cuentan.",
        "tr_fig_caption": "Transiciones de cobertura del suelo, {y1}–{y2}.",
        "tr_table_caption": "Las diez mayores transiciones, {y1}–{y2}.",
        "tr_reading": "En total, {total} cambiaron de clase. La mayor transición fue de {a} a {b} ({ha}, {pct} de la superficie modificada).",
        "tr_none": "Ningún píxel cambió de clase entre los dos años.",
        "col_from": "De ({y})",
        "col_to": "A ({y})",
        "col_area_ha": "Superficie (ha)",
        "col_share_changed": "% de la superficie modificada",
        "gfc_intro": "Hansen Global Forest Change (UMD, v1.13) cartografía la cobertura del dosel arbóreo en 2000, el año de pérdida de cobertura arbórea por reemplazo del rodal de 2001 a 2025 y la ganancia de cobertura arbórea entre 2000 y 2012, a 30 m.",
        "gfc_fig_caption": "Pérdida de cobertura arbórea por año dentro del territorio (Hansen GFC).",
        "gfc_table_caption": "Resumen Hansen GFC del territorio.",
        "gfc_m_cover": "Cobertura arbórea en 2000 (dosel > 0%)",
        "gfc_m_loss": "Pérdida total 2001–{last}",
        "gfc_m_loss_pct": "Pérdida como % de la cobertura arbórea de 2000",
        "gfc_m_gain": "Ganancia 2000–2012 (sin fecha)",
        "gfc_reading": "Hansen registra {loss} de pérdida de cobertura arbórea entre 2001 y {last}, {pct} de la cobertura de 2000; el año con mayor pérdida fue {year} ({ha}).",
        "gfc_reading_none": "Hansen no registra pérdida de cobertura arbórea dentro del territorio entre 2001 y 2025.",
        "col_metric": "Indicador",
        "col_value": "Valor",
        "glad_intro": "GLAD GLCLU2020 (v2) cartografía la cobertura y el uso del suelo mundial a 30 m para 2000, 2005, 2010, 2015 y 2020.",
        "glad_fig_caption": "Clases de cobertura del suelo GLAD dentro del territorio, {year}.",
        "glad_table_caption": "Las cinco mayores clases GLAD, {year}.",
        "glad_reading": "En {year}, la mayor clase GLAD dentro del territorio fue {cls}, con {ha} ({pct} de la superficie clasificada).",
        "mw_intro": "El análisis en múltiples ventanas encadena las transiciones de MapBiomas en ventanas consecutivas: {years}.",
        "mw_fig_caption": "Transiciones de cobertura del suelo en {n} ventanas, {first}–{last}.",
        "tl_intro": "Series anuales de pérdida de cobertura arbórea e indicadores relacionados de MapBiomas dentro del territorio, {y0}–{y1}.",
        "tl_fig_caption": "Línea de tiempo de la deforestación, {y0}–{y1}.",
        "tl_note": "Las franjas de color detrás de las series marcan mandatos políticos e hitos de políticas públicas. Son solo referencias temporales; el gráfico no les atribuye ningún cambio.",
        "buf_intro": "La zona de amortiguamiento es un anillo de {km} km alrededor del territorio, analizado con los mismos conjuntos de datos y años.",
        "buf_table_caption": "Territorio y zona de amortiguamiento comparados.",
        "buf_forest_note": "Bosque = clases de bosque natural de MapBiomas 3, 4, 5, 6 y 49; p.p. = puntos porcentuales.",
        "buf_m_forest_y": "Cobertura forestal {y} (%)",
        "buf_m_forest_change": "Variación de la cobertura forestal {y1}–{y2} (p.p.)",
        "buf_m_gfc": "Pérdida GFC, % de la cobertura arbórea de 2000",
        "buf_reading": "En el mismo período, la cobertura forestal varió {t} p.p. dentro del territorio y {b} p.p. en su zona de amortiguamiento de {km} km, una diferencia de {gap} p.p.",
        "buf_reading_gfc": "La pérdida Hansen equivale a {t} de la cobertura arbórea de 2000 dentro del territorio y a {b} en la zona de amortiguamiento.",
        "col_territory": "Territorio",
        "col_buffer": "Amortiguamiento",
        "col_difference": "Amortiguamiento menos territorio",
        "methods_intro": "Conjuntos de datos, bandas, escalas y reductores de cada sección. El informe reutiliza los resultados del análisis; nada se recalculó al exportar.",
        "prov_mapbiomas": "Cobertura del suelo MapBiomas",
        "prov_transitions": "Transiciones MapBiomas",
        "prov_gfc": "Hansen GFC",
        "prov_glad": "Cobertura del suelo GLAD",
        "prov_mw": "Transiciones en múltiples ventanas",
        "prov_timeline": "Línea de tiempo de la deforestación",
        "prov_imagery": "Imágenes de los mapas",
        "prov_buffer": "Zona de amortiguamiento",
        "prov_note_area": "Superficie = número de píxeles × superficie media del píxel de la región a 30 m.",
        "prov_note_buffer": "Anillo exterior de {km} km alrededor del límite, analizado con los mismos datos.",
        "prov_note_quadrants": "Analizado en {n} partes y sumado.",
        "prov_note_timeline": "Pérdida Hansen por año, más las series de MapBiomas de deforestación, vegetación secundaria y fuego.",
        "prov_note_imagery": "Solo como fondo de los mapas, en ninguna cifra.",
        "prov_note_transitions": "Solo cambios: se excluyen los píxeles que mantuvieron su clase.",
        "attr_mapbiomas": "Proyecto MapBiomas, Colección 10.1 — CC BY-SA 4.0",
        "attr_hansen": "Hansen/UMD/Google/USGS/NASA, Global Forest Change — CC BY 4.0",
        "attr_glad": "GLAD/UMD, GLCLU2020 — CC BY 4.0",
        "attr_ti": "Límites y atributos de las Tierras Indígenas: FUNAI",
        "attr_uc": "Límites y atributos de las Unidades de Conservación: CNUC/MMA",
        "attr_ibge": "Límites estatales (mapa de ubicación): IBGE",
        "app_classes_caption": "Todas las clases de cobertura del suelo dentro del territorio, {y}.",
        "app_change_pct_caption": "Variación relativa por clase de cobertura del suelo, {y1}–{y2}.",
        "app_buffer_cmp_caption": "Zona de amortiguamiento: superficie por clase de cobertura del suelo, {y1} y {y2}.",
        "app_buffer_gl_caption": "Zona de amortiguamiento: ganancias y pérdidas por clase, {y1}–{y2}.",
        "app_buffer_classes_caption": "Todas las clases de cobertura del suelo en la zona de amortiguamiento, {y1} vs {y2}.",
        "app_matrix_caption": "Matriz de transiciones, {y1}–{y2}.",
        "app_transitions_caption": "Todas las transiciones, {y1}–{y2}.",
        "fig_render_failed": "no se pudo generar el gráfico",
    },
    # ------------------------------------------------------------------ fr
    "fr": {
        "report_title": "Rapport territorial",
        "kind_ti": "Terre indigène",
        "kind_uc": "Unité de conservation",
        "sec_identification": "Identification",
        "sec_about": "À propos de ce rapport",
        "sec_maps": "Cartes",
        "sec_landcover": "Occupation du sol {y1} vs {y2}",
        "sec_gains_losses": "Gains et pertes",
        "sec_transitions": "Transitions",
        "sec_gfc": "Hansen Global Forest Change",
        "sec_glad": "Occupation du sol GLAD",
        "sec_multi_window": "Transitions sur plusieurs fenêtres",
        "sec_timeline": "Chronologie de la déforestation",
        "sec_buffer": "Territoire vs zone tampon",
        "sec_methods": "Méthodes et données",
        "sec_citation": "Sources et citation",
        "sec_appendix": "Annexe",
        "id_name": "Nom",
        "id_code": "Code FUNAI",
        "id_ethnicity": "Peuple(s)",
        "id_phase": "Phase",
        "id_modality": "Modalité",
        "id_uf": "État(s)",
        "id_municipality": "Commune(s)",
        "id_area_official": "Superficie officielle",
        "id_area_computed": "Superficie calculée (MapBiomas {y})",
        "id_ladder": "Étapes de la démarcation",
        "stage_em_estudo": "en étude",
        "stage_delimitada": "délimitée",
        "stage_declarada": "déclarée",
        "stage_homologada": "homologuée",
        "stage_regularizada": "régularisée",
        "id_cnuc": "Code CNUC",
        "id_group": "Groupe",
        "id_category": "Catégorie",
        "id_sphere": "Sphère",
        "id_creation_year": "Année de création",
        "id_years": "Années comparées",
        "id_mapbiomas": "Collection MapBiomas",
        "id_gfc": "Hansen GFC",
        "id_glad": "Occupation du sol GLAD",
        "id_buffer": "Zone tampon",
        "id_buffer_width": "anneau de {km} km autour de la limite",
        "id_not_analysed": "non analysée",
        "id_caption_ti": "Attributs du fichier de limites de la FUNAI ; superficie calculée à partir du nombre de pixels MapBiomas.",
        "id_caption_uc": "Attributs du fichier de limites du CNUC ; superficie calculée à partir du nombre de pixels MapBiomas.",
        "locator_label": "Localisation au Brésil",
        "about_para": "Ce rapport porte sur **{name}**{period}{buffer}. Il présente des données, pas un verdict : les chiffres décrivent ce que chaque jeu de données enregistre à l'intérieur de la limite, et les différences entre années ou entre le territoire et ses environs sont décrites sans être attribuées à une cause.",
        "about_period": " pour les années {y1} et {y2}",
        "about_buffer": ", avec une zone tampon de {km} km autour",
        "about_quadrants": "La zone a été analysée en {n} parties, additionnées dans chaque tableau et graphique.",
        "reason_not_run": "non calculé pour cette zone",
        "reason_excluded": "exclu dans les options du rapport",
        "reason_no_buffer": "aucune zone tampon n'a été analysée",
        "reason_maps_failed": "les images des cartes n'ont pas pu être obtenues",
        "reason_appendix_batch": "non produit dans les traitements par lots",
        "contents_appendix": "Annexe (tableaux complets)",
        "maps_intro": "Les couches de classes et les images proviennent d'Earth Engine ; les contours sont tracés à partir du fichier de limites. Le trait plein est la limite du territoire et le trait tireté le bord extérieur de la zone tampon.",
        "map_mb_caption": "Occupation du sol MapBiomas, {y}.",
        "map_gfc_caption": "Année de perte du couvert arboré (Hansen GFC, 2001–2025) sur l'image de fond.",
        "map_img_caption": "Image de fond avec la limite du territoire et la zone tampon.",
        "maps_no_imagery": "La zone s'étend sur plus de 300 km : aucune image de fond n'est tracée, les couches de classes apparaissent sur fond blanc.",
        "maps_failed": "Les images des cartes n'ont pas pu être obtenues depuis Earth Engine : {err}",
        "legend_boundary": "Limite du territoire",
        "legend_buffer": "Zone tampon ({km} km)",
        "legend_loss": "Perte {a}–{b}",
        "lc_intro": "La Collection 10.1 de MapBiomas classe chaque pixel de 30 m du Brésil en classes d'occupation et d'usage du sol pour chaque année depuis 1985.",
        "lc_fig_caption": "Superficie par classe d'occupation du sol dans le territoire, {y1} et {y2}.",
        "lc_table_caption": "Classes d'occupation du sol dans le territoire, {y1} vs {y2}.",
        "lc_reading": "Entre {y1} et {y2}, {cls} dans le territoire est passée de {a1} ({p1}) à {a2} ({p2}), {direction}.",
        "dir_up": "soit une hausse de {d}",
        "dir_down": "soit une baisse de {d}",
        "dir_same": "sans changement",
        "lc_second_up": "{cls} a augmenté de {d}.",
        "lc_second_down": "{cls} a diminué de {d}.",
        "col_class": "Classe",
        "col_area_y": "{y} (ha)",
        "col_delta_ha": "Variation (ha)",
        "col_delta_pct": "Variation (%)",
        "col_share": "Part (%)",
        "gl_intro": "Variation nette par classe entre {y1} et {y2} : les barres positives sont la superficie gagnée, les négatives la superficie perdue.",
        "gl_fig_caption": "Gains et pertes par classe d'occupation du sol, {y1}–{y2}.",
        "gl_reading": "Toutes classes confondues, les gains totalisent {g} et les pertes {l}. Le gain le plus important concerne {cg} ({dg}) et la perte la plus importante {cl} ({dl}).",
        "tr_intro": "Les transitions donnent la superficie des pixels qui ont changé de classe entre {y1} et {y2} ; les pixels qui ont gardé leur classe ne sont pas comptés.",
        "tr_fig_caption": "Transitions d'occupation du sol, {y1}–{y2}.",
        "tr_table_caption": "Les dix plus grandes transitions, {y1}–{y2}.",
        "tr_reading": "Au total, {total} ont changé de classe. La plus grande transition va de {a} à {b} ({ha}, {pct} de la superficie modifiée).",
        "tr_none": "Aucun pixel n'a changé de classe entre les deux années.",
        "col_from": "De ({y})",
        "col_to": "Vers ({y})",
        "col_area_ha": "Superficie (ha)",
        "col_share_changed": "% de la superficie modifiée",
        "gfc_intro": "Hansen Global Forest Change (UMD, v1.13) cartographie le couvert arboré en 2000, l'année de perte du couvert arboré par remplacement du peuplement de 2001 à 2025 et le gain de couvert arboré entre 2000 et 2012, à 30 m.",
        "gfc_fig_caption": "Perte du couvert arboré par année dans le territoire (Hansen GFC).",
        "gfc_table_caption": "Synthèse Hansen GFC du territoire.",
        "gfc_m_cover": "Couvert arboré en 2000 (canopée > 0 %)",
        "gfc_m_loss": "Perte totale 2001–{last}",
        "gfc_m_loss_pct": "Perte en % du couvert arboré de 2000",
        "gfc_m_gain": "Gain 2000–2012 (non daté)",
        "gfc_reading": "Hansen enregistre {loss} de perte du couvert arboré entre 2001 et {last}, soit {pct} du couvert de 2000 ; l'année la plus forte est {year} ({ha}).",
        "gfc_reading_none": "Hansen n'enregistre aucune perte du couvert arboré dans le territoire entre 2001 et 2025.",
        "col_metric": "Indicateur",
        "col_value": "Valeur",
        "glad_intro": "GLAD GLCLU2020 (v2) cartographie l'occupation et l'usage du sol mondiaux à 30 m pour 2000, 2005, 2010, 2015 et 2020.",
        "glad_fig_caption": "Classes d'occupation du sol GLAD dans le territoire, {year}.",
        "glad_table_caption": "Les cinq plus grandes classes GLAD, {year}.",
        "glad_reading": "En {year}, la plus grande classe GLAD dans le territoire est {cls}, avec {ha} ({pct} de la superficie classée).",
        "mw_intro": "L'analyse sur plusieurs fenêtres enchaîne les transitions MapBiomas sur des fenêtres consécutives : {years}.",
        "mw_fig_caption": "Transitions d'occupation du sol sur {n} fenêtres, {first}–{last}.",
        "tl_intro": "Séries annuelles de perte du couvert arboré et d'indicateurs MapBiomas associés dans le territoire, {y0}–{y1}.",
        "tl_fig_caption": "Chronologie de la déforestation, {y0}–{y1}.",
        "tl_note": "Les bandes colorées derrière les séries marquent les mandats politiques et les jalons des politiques publiques. Ce sont de simples repères temporels ; le graphique ne leur attribue aucun changement.",
        "buf_intro": "La zone tampon est un anneau de {km} km autour du territoire, analysé avec les mêmes jeux de données et années.",
        "buf_table_caption": "Territoire et zone tampon comparés.",
        "buf_forest_note": "Forêt = classes de forêt naturelle MapBiomas 3, 4, 5, 6 et 49 ; p.p. = points de pourcentage.",
        "buf_m_forest_y": "Couvert forestier {y} (%)",
        "buf_m_forest_change": "Variation du couvert forestier {y1}–{y2} (p.p.)",
        "buf_m_gfc": "Perte GFC, % du couvert arboré de 2000",
        "buf_reading": "Sur la même période, le couvert forestier a varié de {t} p.p. dans le territoire et de {b} p.p. dans sa zone tampon de {km} km, soit un écart de {gap} p.p.",
        "buf_reading_gfc": "La perte Hansen représente {t} du couvert arboré de 2000 dans le territoire et {b} dans la zone tampon.",
        "col_territory": "Territoire",
        "col_buffer": "Zone tampon",
        "col_difference": "Zone tampon moins territoire",
        "methods_intro": "Jeux de données, bandes, échelles et réducteurs de chaque section. Le rapport réutilise les résultats de l'analyse ; rien n'a été recalculé à l'export.",
        "prov_mapbiomas": "Occupation du sol MapBiomas",
        "prov_transitions": "Transitions MapBiomas",
        "prov_gfc": "Hansen GFC",
        "prov_glad": "Occupation du sol GLAD",
        "prov_mw": "Transitions sur plusieurs fenêtres",
        "prov_timeline": "Chronologie de la déforestation",
        "prov_imagery": "Images des cartes",
        "prov_buffer": "Zone tampon",
        "prov_note_area": "Superficie = nombre de pixels × superficie moyenne du pixel de la zone à 30 m.",
        "prov_note_buffer": "Anneau extérieur de {km} km autour de la limite, analysé avec les mêmes données.",
        "prov_note_quadrants": "Analysé en {n} parties puis additionné.",
        "prov_note_timeline": "Perte Hansen par année, plus les séries MapBiomas de déforestation, de végétation secondaire et de feu.",
        "prov_note_imagery": "Utilisées uniquement comme fond de carte, dans aucun chiffre.",
        "prov_note_transitions": "Changements seulement : les pixels qui ont gardé leur classe sont exclus.",
        "attr_mapbiomas": "Projet MapBiomas, Collection 10.1 — CC BY-SA 4.0",
        "attr_hansen": "Hansen/UMD/Google/USGS/NASA, Global Forest Change — CC BY 4.0",
        "attr_glad": "GLAD/UMD, GLCLU2020 — CC BY 4.0",
        "attr_ti": "Limites et attributs des Terres indigènes : FUNAI",
        "attr_uc": "Limites et attributs des Unités de conservation : CNUC/MMA",
        "attr_ibge": "Limites des États (carte de localisation) : IBGE",
        "app_classes_caption": "Toutes les classes d'occupation du sol dans le territoire, {y}.",
        "app_change_pct_caption": "Variation relative par classe d'occupation du sol, {y1}–{y2}.",
        "app_buffer_cmp_caption": "Zone tampon : superficie par classe d'occupation du sol, {y1} et {y2}.",
        "app_buffer_gl_caption": "Zone tampon : gains et pertes par classe, {y1}–{y2}.",
        "app_buffer_classes_caption": "Toutes les classes d'occupation du sol dans la zone tampon, {y1} vs {y2}.",
        "app_matrix_caption": "Matrice de transitions, {y1}–{y2}.",
        "app_transitions_caption": "Toutes les transitions, {y1}–{y2}.",
        "fig_render_failed": "le graphique n'a pas pu être généré",
    },
}


def missing_keys() -> Dict[str, List[str]]:
    """Template keys present in English but absent from another language."""
    en = set(TEXT["en"])
    return {lang: sorted(en - set(TEXT[lang])) for lang in LANGS if lang != "en"}


def s(key: str, lang: str, **kw) -> str:
    """A template in ``lang`` (fallback en), filled with ``kw``."""
    table = TEXT.get(lang) or TEXT["en"]
    text = table.get(key) or TEXT["en"][key]
    return text.format(**kw) if kw else text


def km_label(km: Optional[float], lang: str) -> str:
    return fmt_num(km, 0 if km is None or float(km).is_integer() else 1, lang)


# --------------------------------------------------------------------------- #
# Reading sentences — (numbers, lang) → str. Numbers come from the section's
# own table rows; only sums and shares of those rows are taken here.
# --------------------------------------------------------------------------- #

def _direction(delta: float, lang: str) -> str:
    if abs(delta) < 0.05:
        return s("dir_same", lang)
    key = "dir_up" if delta > 0 else "dir_down"
    return s(key, lang, d=fmt_ha(abs(delta), 0, lang))


def landcover_reading(rows: Sequence[Tuple[str, float, float]], y1, y2,
                      lang: str) -> str:
    """``rows``: (class name, area y1 ha, area y2 ha). One sentence on the
    largest class of y1, one on the class with the largest change among the
    others."""
    rows = [r for r in rows if (r[1] or 0) > 0 or (r[2] or 0) > 0]
    if not rows:
        return ""
    tot1 = sum(r[1] or 0 for r in rows) or 1.0
    tot2 = sum(r[2] or 0 for r in rows) or 1.0
    top = max(rows, key=lambda r: r[1] or 0)
    a1, a2 = top[1] or 0.0, top[2] or 0.0
    text = s("lc_reading", lang, y1=y1, y2=y2, cls=top[0],
             a1=fmt_ha(a1, 0, lang), p1=fmt_pct(a1 / tot1 * 100, 1, lang),
             a2=fmt_ha(a2, 0, lang), p2=fmt_pct(a2 / tot2 * 100, 1, lang),
             direction=_direction(a2 - a1, lang))
    others = [r for r in rows if r is not top]
    if others:
        mover = max(others, key=lambda r: abs((r[2] or 0) - (r[1] or 0)))
        d = (mover[2] or 0) - (mover[1] or 0)
        if abs(d) >= 0.5:
            key = "lc_second_up" if d > 0 else "lc_second_down"
            text += " " + s(key, lang, cls=mover[0], d=fmt_ha(abs(d), 0, lang))
    return text


def gains_losses_reading(rows: Sequence[Tuple[str, float, float]], lang: str) -> str:
    deltas = [(r[0], (r[2] or 0) - (r[1] or 0)) for r in rows]
    gains = [d for d in deltas if d[1] > 0]
    losses = [d for d in deltas if d[1] < 0]
    if not gains and not losses:
        return ""
    g = sum(d[1] for d in gains)
    lo = sum(d[1] for d in losses)
    cg = max(gains, key=lambda d: d[1]) if gains else ("—", 0.0)
    cl = min(losses, key=lambda d: d[1]) if losses else ("—", 0.0)
    return s("gl_reading", lang, g=fmt_ha(g, 0, lang), l=fmt_ha(abs(lo), 0, lang),
             cg=cg[0], dg=fmt_signed(cg[1], 0, lang) + " ha",
             cl=cl[0], dl=fmt_signed(cl[1], 0, lang) + " ha")


def transitions_reading(top: Sequence[Tuple[str, str, float]], total: float,
                        lang: str) -> str:
    if not top or total <= 0:
        return s("tr_none", lang)
    a, b, ha = top[0]
    return s("tr_reading", lang, total=fmt_ha(total, 0, lang), a=a, b=b,
             ha=fmt_ha(ha, 0, lang), pct=fmt_pct(ha / total * 100, 1, lang))


def gfc_reading(loss_ha: float, cover_ha: float, by_year: Sequence[Tuple[int, float]],
                lang: str) -> str:
    if not by_year or loss_ha <= 0:
        return s("gfc_reading_none", lang)
    year, ha = max(by_year, key=lambda r: r[1])
    last = max(y for y, _ in by_year)
    pct = loss_ha / cover_ha * 100 if cover_ha > 0 else None
    return s("gfc_reading", lang, loss=fmt_ha(loss_ha, 0, lang), last=last,
             pct=fmt_pct(pct, 1, lang), year=year, ha=fmt_ha(ha, 0, lang))


def glad_reading(year, cls: str, ha: float, total: float, lang: str) -> str:
    return s("glad_reading", lang, year=year, cls=cls, ha=fmt_ha(ha, 0, lang),
             pct=fmt_pct(ha / total * 100 if total else None, 1, lang))


def buffer_reading(t_pp: Optional[float], b_pp: Optional[float], km, lang: str) -> str:
    if t_pp is None or b_pp is None:
        return ""
    return s("buf_reading", lang, t=fmt_signed(t_pp, 1, lang), b=fmt_signed(b_pp, 1, lang),
             km=km_label(km, lang), gap=fmt_signed(b_pp - t_pp, 1, lang))


def buffer_gfc_reading(t_pct: Optional[float], b_pct: Optional[float], lang: str) -> str:
    if t_pct is None or b_pct is None:
        return ""
    return s("buf_reading_gfc", lang, t=fmt_pct(t_pct, 1, lang), b=fmt_pct(b_pct, 1, lang))
